# This is a basic workflow to help you get started with Actions

name: Latex Compilation

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: LaTeX linter
        # You may pin to the exact commit or the version.
        # uses: colinaaa/chktex-action@5dda098b973d69cdc61ace93fa7bfcef39efaade
        # uses: colinaaa/chktex-action@v1.1.2

      - name: LaTeX Action
        # You may pin to the exact commit or the version.
        # uses: fudan-mse/latex-action@eb2eb7ba472011213ac0a6286fd776494623362c
        uses: fudan-mse/latex-action@v0.0.1
        with:
          # The root LaTeX file to be compiled
          root_file: main.tex
          # The LaTeX engine to be invoked
          compiler: pdflatex # optional, default is latexmk
          # Extra arguments to be passed to the LaTeX engine
          # args: # optional, default is -pdf -file-line-error -interaction=nonstopmode
          # Install extra packages by tlmgr
          # extra_packages: # optional
          # Install extra packages by apk
          # extra_system_packages: # optional
      - uses: actions/upload-artifact@v2
        with:
          name: Thesis.pdf # output file
          path: main.pdf   # path to file
