# BASIC WORKFLOW
name: Latex Compilation

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: blang/latex:ubuntu

    # Steps represent a sequence of tasks that will be executed as part of the job
    # Steps will now run on the container
    steps:
      # Check out repository
      - uses: actions/checkout@v2

      - name: Log container information
        run: cat /etc/os-release

      - name: Compile latex document
        run: make main

      # Uploads the output pdf file to artefacts
      - uses: actions/upload-artifact@v2
        with:
          name: Thesis.pdf # output file
          path: main.pdf   # path to file
